# Generated by Django 4.1.7 on 2023-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=100)),
                ('gender', models.TextField()),
                ('address', models.TextField()),
                ('ethnic', models.TextField()),
                ('department', models.TextField()),
                ('majors', models.TextField()),
                ('classroom', models.CharField(max_length=1000)),
            ],
        ),
    ]
