# Generated by Django 4.2 on 2024-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='price',
            field=models.FloatField(),
        ),
    ]
